# Generated by Django 4.2.5 on 2023-09-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='SpecName',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_names', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=80)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.specname')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=247)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('available', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('specs', models.ManyToManyField(blank=True, related_name='products', to='product.spec')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
